version: "3"
services:
    web:
        build: src/app
        ports:
            - "8080:5000"
        depends_on:
            - api
    api:
        build: src/api
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        ports:
            - "1401:1433"
        environment:
            SA_PASSWORD: "Qwer1234*"
            ACCEPT_EULA: "Y"