version: "3"
services:
    web:
        build: src/Client
        ports:
            - "80:5000"
        depends_on:
            - api
    api:
        build: src/Server/Api
        ports:
            - "3000:80"
        depends_on:
            - db
    migration:
        build: "src/Server/Database"
        depends_on: 
            - db
    db:
        image: "microsoft/mssql-server-linux"
        volumes:
            - mssqldata:/var/lib/mssql
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Qwer1234*"
            ACCEPT_EULA: "Y"

volumes:
    mssqldata: