ALTER TABLE Wine ADD [Status] int
ALTER TABLE Wine ADD Vintage VARCHAR(5)
ALTER TABLE Wine ADD VinmonopoletUrl VARCHAR(200)
ALTER TABLE Wine ADD [Type] VARCHAR(50)
ALTER TABLE Wine ADD Producer VARCHAR(200)
ALTER TABLE Wine ADD Country VARCHAR(200)
ALTER TABLE Wine ADD Area VARCHAR(200)
ALTER TABLE Wine ADD Fruit VARCHAR(200)
ALTER TABLE Wine ADD Price FLOAT
ALTER TABLE Wine ADD BoughtDate DATE
ALTER TABLE Wine ADD Storage bit
        